#Server embedded configuration

#Spring configuration
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/holoo-weather-service
    username: root
    password: pskPSK258##
    hikari:
      pool-name: weather-service-connection
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 10000
      data-source-properties:
        cacheDefaultTimeZone: false
        connectionTimeZone: SERVER
        forceConnectionTimeZoneToSession: true
  jpa:
    database: mysql
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#Custome application configuration

#Logback logging configuration
